package ssm.bean;

import java.util.Date;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbggenerated Tue May 11 19:24:00 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacherName
     *
     * @mbggenerated Tue May 11 19:24:00 CST 2021
     */
    private String teachername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.subject_name
     *
     * @mbggenerated Tue May 11 19:24:00 CST 2021
     */
    private String subjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.address
     *
     * @mbggenerated Tue May 11 19:24:00 CST 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.birth_date
     *
     * @mbggenerated Tue May 11 19:24:00 CST 2021
     */
    private Date birthDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.id
     *
     * @return the value of teacher.id
     *
     * @mbggenerated Tue May 11 19:24:00 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.id
     *
     * @param id the value for teacher.id
     *
     * @mbggenerated Tue May 11 19:24:00 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacherName
     *
     * @return the value of teacher.teacherName
     *
     * @mbggenerated Tue May 11 19:24:00 CST 2021
     */
    public String getTeachername() {
        return teachername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacherName
     *
     * @param teachername the value for teacher.teacherName
     *
     * @mbggenerated Tue May 11 19:24:00 CST 2021
     */
    public void setTeachername(String teachername) {
        this.teachername = teachername == null ? null : teachername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.subject_name
     *
     * @return the value of teacher.subject_name
     *
     * @mbggenerated Tue May 11 19:24:00 CST 2021
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.subject_name
     *
     * @param subjectName the value for teacher.subject_name
     *
     * @mbggenerated Tue May 11 19:24:00 CST 2021
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.address
     *
     * @return the value of teacher.address
     *
     * @mbggenerated Tue May 11 19:24:00 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.address
     *
     * @param address the value for teacher.address
     *
     * @mbggenerated Tue May 11 19:24:00 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.birth_date
     *
     * @return the value of teacher.birth_date
     *
     * @mbggenerated Tue May 11 19:24:00 CST 2021
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.birth_date
     *
     * @param birthDate the value for teacher.birth_date
     *
     * @mbggenerated Tue May 11 19:24:00 CST 2021
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    @Override
    public String toString() {
        return "Teacher{" +
                "id=" + id +
                ", teachername='" + teachername + '\'' +
                ", subjectName='" + subjectName + '\'' +
                ", address='" + address + '\'' +
                ", birthDate=" + birthDate +
                '}';
    }
}